### ISSUE TITLE
Available button not in sync with the data changes

### ISSUE THREAD

**Issue by sshaaf** [Emergency-Response-Demo/mobile-app#6]
To Reproduce:
Login to Emergency console. 
Set your self to available.
Refresh the page. 
Available button starts to show up again.

**Comment by sshaaf** [comment]
@wei-lee

**Comment by wei-lee** [comment]
@sshaaf thanks for creating the issue. I looked into briefly, and I think there are 2 ways that we could fix this:

The first way is to periodically get/read the responder status data in the client app and update the ui accordingly. This approach is quicker, and doesn't require any changes in other components. However, it does mean the client app need to polling data from the server. 

The second approach is to update the `ResponderService` to send a `ResponderUpdatedEvent` message when the status of a responder is changed (see https://github.com/Emergency-Response-Demo/responder-service/blob/master/src/main/java/com/redhat/cajun/navy/responder/service/ResponderService.java#L152), and the client will listen for this event and update the ui whenever the status of the user changes. This feels like the right approach, as I think there should be messages published whenever the status of responders change? But obviously this means we need to update 2 components to fix this issue.

what do you think? Or is there some other events I should listen to that will allow to know the status of a responder has changed?

Thanks.

**Comment by sshaaf** [comment]
The issue is e.g. when you refresh the browser, then the button state goes away. perhaps when the first time the user logs in, we do not get the status of the Responder from the service. If we do that, I am guessing we might not need to make any other changes to backend.

**Comment by wei-lee** [comment]
@sshaaf ah, right. I see what you mean. Sorry I misunderstood the issue. It should be an easy fix then.

**Comment by wei-lee** [comment]
Linked PR is merged, problem solved.
